# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres:15.0
    restart: always
    volumes:
     - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: cefetmg
      POSTGRES_DB: management
      POSTGRES_USER: root
    ports:
      - 5432:5432
volumes:
  pgdata: