
services:
#  app:
#    build: .
#    ports:
#      - "3001:3001"
#    environment:
#      - NODE_ENV=development
#      - DB_HOST=db
#      - DB_PORT=5432
#      - DB_USER=root
#      - DB_PASS=cefetmg
#      - DB_NAME=study_time
#      - DB_APP_PORT=3001
#    depends_on:
#      - db
  db:
    image: postgres:15.0
    container_name: postgres_study_time
    environment:
      POSTGRES_PASSWORD: cefetmg
      POSTGRES_DB: study_time
      POSTGRES_USER: root
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: