# Use postgres/example user/password credentials
version: '3.8'

services:
  db:
    image: postgres:15.0
    restart: always
    container_name: postgres_study_time
    environment:
      POSTGRES_PASSWORD: cefetmg
      POSTGRES_DB: study_time
      POSTGRES_USER: root
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: